### PR TITLE
fixed NA handling and padded heatmap

### LINKED ISSUE #42: "Padded" heatmap
I apologise if I'm missing something, but after looking around I haven't found a way to implement the xgap and ymap traces in order to add some white space between the "bricks". Please let me know if there is any way to do this or if it could be implemented.

Thanks for your work developing this package.

### LINKED ISSUE #49: Handling of NAs in function discrete_coloring_range()
This part within the function discrete_coloring_range() does not handle may existing NA-values in df$category as expected. 
When NAs are present in df$category, an error will always occur due to differing lengths between df$category (where NA is counted) and color_palette.

existing code:
https://github.com/VerkehrsbetriebeZuerich/catmaply/blob/f01563a9d9627caaace340db142dde8bbc4cabc3/R/utils.R#L64-L77

fixed code with filtered NAs:
```r
  if ((length(unique(df$category[!is.na(df$category)])) * 2) == length(color_palette)) {
    discrete_colorbar <- TRUE
  } else if (length(unique(df$category[!is.na(df$category)])) == length(color_palette)) {
    exp_col_palette <- c()
    for (col in color_palette) exp_col_palette <- c(exp_col_palette, col, col)
    color_palette <- exp_col_palette
  } else {
    stop(
      paste(
        "Parameter 'color_palette' must have the same or twice ",
        "the length of vcategory parameter."
      )
    )
  }
```

### PR DESCRIPTION
**Pull request by christophbaur**
Close #49 Close #42

### CODE REVIEW

File: DESCRIPTION [hunk 1]
```diff
@@ -1,9 +1,10 @@
...
 Title: Heatmap for Categorical Data using 'plotly'
-Version: 0.9.4
+Version: 0.9.5
 Authors@R: c(
       person("Yves", "Mauron", email="ypmauron@gmail.com", role=c("aut", "cre")),
-      person(given="Trivadis AG", role="cph")
+      person(given="Trivadis AG", role="cph"),
+      person("Christoph", "Baur", role=c("aut"))
     )
 Maintainer: Yves Mauron <ypmauron@gmail.com>
```
Comment (yvesmauron) [inline DESCRIPTION]: Please change Maintainer to VBZ group e-mail.

File: tests/testthat/test-catmaply.R [hunk 2]
```diff
@@ -933,5 +957,37 @@ test_that("colorbar - plot.R", {
     )
   )
 
+  # color palette with static legend and NAs in occ_category, occ_cat_name and occupancy
+  df_na <- vbz[[1]] %>% dplyr::filter(.data$vehicle == "PO")%>%
```
Comment (yvesmauron) [inline tests/testthat/test-catmaply.R:961]: Example to for testing the changes

File: DESCRIPTION (hunk 1 above)
Comment (christophbaur) [reply DESCRIPTION]: done

**Comment by yvesmauron** [comment]
LGTM - looks good to me.

Maybe additional data type checks could be added in plot.R (also applies for other parameters).

**Review by yvesmauron — APPROVED** [review]
LGTM - looks good to me.

Maybe additional data type checks could be added in plot.R (also applies for other parameters that were not changed in this PR).

**Review by yvesmauron — APPROVED** [review]
